//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDLCReport.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SafetyAppDBEntities : DbContext
    {
        public SafetyAppDBEntities()
            : base("name=SafetyAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_business_unit> tb_business_unit { get; set; }
        public virtual DbSet<tb_project> tb_project { get; set; }
        public virtual DbSet<tb_region> tb_region { get; set; }
        public virtual DbSet<tb_user_profile> tb_user_profile { get; set; }
        public virtual DbSet<tb_ehs_req_area> tb_ehs_req_area { get; set; }
        public virtual DbSet<tb_ehs_req_area_praram> tb_ehs_req_area_praram { get; set; }
        public virtual DbSet<tb_ehs_requirement_master> tb_ehs_requirement_master { get; set; }
        public virtual DbSet<tb_ehs_scorecard_master> tb_ehs_scorecard_master { get; set; }
        public virtual DbSet<tb_ehs_assessment_score> tb_ehs_assessment_score { get; set; }
        public virtual DbSet<tb_ehs_assessment_score_neg> tb_ehs_assessment_score_neg { get; set; }
        public virtual DbSet<tb_ehs_assessment_score_transaction> tb_ehs_assessment_score_transaction { get; set; }
    
        public virtual ObjectResult<spMisReportDataByID_Result> spMisReportDataByID(Nullable<int> misReportID)
        {
            var misReportIDParameter = misReportID.HasValue ?
                new ObjectParameter("MisReportID", misReportID) :
                new ObjectParameter("MisReportID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMisReportDataByID_Result>("spMisReportDataByID", misReportIDParameter);
        }
    
        public virtual ObjectResult<spMisReportDataByID1_Result> spMisReportDataByID1(Nullable<int> misReportID)
        {
            var misReportIDParameter = misReportID.HasValue ?
                new ObjectParameter("MisReportID", misReportID) :
                new ObjectParameter("MisReportID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMisReportDataByID1_Result>("spMisReportDataByID1", misReportIDParameter);
        }
    
        public virtual ObjectResult<spMisReportDataByID2_Result> spMisReportDataByID2(Nullable<int> misReportID)
        {
            var misReportIDParameter = misReportID.HasValue ?
                new ObjectParameter("MisReportID", misReportID) :
                new ObjectParameter("MisReportID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMisReportDataByID2_Result>("spMisReportDataByID2", misReportIDParameter);
        }
    
        public virtual ObjectResult<spMisReportDataByID3_Result> spMisReportDataByID3(Nullable<int> misReportID)
        {
            var misReportIDParameter = misReportID.HasValue ?
                new ObjectParameter("MisReportID", misReportID) :
                new ObjectParameter("MisReportID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMisReportDataByID3_Result>("spMisReportDataByID3", misReportIDParameter);
        }
    }
}
