//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDLCReport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ehs_assessment_score_transaction
    {
        public int EhsAssesmentTransactionID { get; set; }
        public Nullable<int> EhsAssesmentID { get; set; }
        public Nullable<int> RequirementID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> ParamID { get; set; }
        public Nullable<bool> IsApplicable { get; set; }
        public Nullable<decimal> ApplicableWeightage { get; set; }
        public string PercentageCompliance { get; set; }
        public Nullable<decimal> Compliance { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> AssessorApplicableWeightage { get; set; }
        public string AssessorPercentageCompliance { get; set; }
        public Nullable<decimal> AccessorCompliance { get; set; }
        public string AccessorRemark { get; set; }
        public Nullable<decimal> Assessor1ApplicableWeightage { get; set; }
        public string Assessor1PercentageCompliance { get; set; }
        public Nullable<decimal> Accessor1Compliance { get; set; }
        public string Accessor1Remark { get; set; }
    
        public virtual tb_ehs_assessment_score tb_ehs_assessment_score { get; set; }
        public virtual tb_ehs_req_area tb_ehs_req_area { get; set; }
        public virtual tb_ehs_req_area_praram tb_ehs_req_area_praram { get; set; }
        public virtual tb_ehs_requirement_master tb_ehs_requirement_master { get; set; }
    }
}
