//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDLCReport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ehs_req_area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ehs_req_area()
        {
            this.tb_ehs_req_area_praram = new HashSet<tb_ehs_req_area_praram>();
            this.tb_ehs_assessment_score_transaction = new HashSet<tb_ehs_assessment_score_transaction>();
        }
    
        public int AreaId { get; set; }
        public int RequirementId { get; set; }
        public Nullable<decimal> SrNo { get; set; }
        public string AreaName { get; set; }
        public Nullable<decimal> TotalWeightagePerCriteria { get; set; }
        public Nullable<int> ScoreCardID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ehs_req_area_praram> tb_ehs_req_area_praram { get; set; }
        public virtual tb_ehs_requirement_master tb_ehs_requirement_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ehs_assessment_score_transaction> tb_ehs_assessment_score_transaction { get; set; }
    }
}
