//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDLCReport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ehs_assessment_score_neg
    {
        public int EhsNegScoreId { get; set; }
        public Nullable<int> EhsAssesmentId { get; set; }
        public string IrType { get; set; }
        public Nullable<int> NegativeMarking { get; set; }
        public Nullable<int> ActualDeduction { get; set; }
        public Nullable<int> Marking { get; set; }
        public string Remark { get; set; }
    
        public virtual tb_ehs_assessment_score tb_ehs_assessment_score { get; set; }
    }
}
