//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDLCReport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ehs_assessment_score
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ehs_assessment_score()
        {
            this.tb_ehs_assessment_score_neg = new HashSet<tb_ehs_assessment_score_neg>();
            this.tb_ehs_assessment_score_transaction = new HashSet<tb_ehs_assessment_score_transaction>();
        }
    
        public int EhsAssesmentId { get; set; }
        public Nullable<int> BusinessUnitID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public int AssessmentBy { get; set; }
        public string Location { get; set; }
        public Nullable<int> NoOfWorkMan { get; set; }
        public int ProjectManagerID { get; set; }
        public int RegionalManagerID { get; set; }
        public int PCH { get; set; }
        public Nullable<int> ScorecardID { get; set; }
        public Nullable<int> RmEHSID { get; set; }
        public Nullable<int> CorpEHSID { get; set; }
        public Nullable<int> RequirementStatusID { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ehs_assessment_score_neg> tb_ehs_assessment_score_neg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ehs_assessment_score_transaction> tb_ehs_assessment_score_transaction { get; set; }
    }
}
