//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDLCReport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ehs_scorecard_master
    {
        public int ScoreCardID { get; set; }
        public string ScoreCardName { get; set; }
        public string ApplicableBusinessUnits { get; set; }
    }
}
