//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDLCReport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_project
    {
        public int ProjectID { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> BusinessUnitID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string Location { get; set; }
    
        public virtual tb_business_unit tb_business_unit { get; set; }
        public virtual tb_region tb_region { get; set; }
    }
}
