//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDLCReport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_region
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_region()
        {
            this.tb_project = new HashSet<tb_project>();
        }
    
        public int RegionID { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> BusinessUnitID { get; set; }
        public Nullable<int> RM_BusinessUnit { get; set; }
        public Nullable<int> RM_Safety { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_project> tb_project { get; set; }
    }
}
