//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDLCReport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user_profile
    {
        public int UserID { get; set; }
        public Nullable<int> UserType { get; set; }
        public string UserEmail { get; set; }
        public string UserMobileNo { get; set; }
        public string UserProfilePic { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> UserBusinessUnitID { get; set; }
        public Nullable<int> UserRegionID { get; set; }
        public Nullable<int> UserProjectID { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public Nullable<System.DateTime> UserLastLoginOn { get; set; }
        public Nullable<System.DateTime> UserProfileLastModifyOn { get; set; }
        public string UserVerificationCode { get; set; }
        public Nullable<int> UserCreatedBy { get; set; }
        public Nullable<System.DateTime> UserCreatedOn { get; set; }
        public Nullable<int> UserApprovedBY { get; set; }
        public Nullable<System.DateTime> UserApprovedOn { get; set; }
        public string UserSignupOTP { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TncAcceptedOn { get; set; }
    }
}
